### ISSUE TITLE
Set up a spare Raspberry Pi with DHCP and git servers

### ISSUE THREAD

**Issue by jwalthour** [first95/FRC2016#16]
It'd be super handy to have a usable "github" while we're in the pits, where there is no internet.

**Comment by jwalthour** [comment]
Should also drop files on there that might come in handy to us and other teams:
- firmware for talons
- wpilib update(s)
- manuals (FRC, Talon, other)

**Comment by jwalthour** [comment]
Project dubbed PitHub.

**Comment by RuggS** [comment]
this is done
