### ISSUE TITLE
Develop closed-loop motor speed control

### ISSUE THREAD

**Issue by jwalthour** [first95/FRC2016#5]

**Comment by jwalthour** [comment]
Currently plan to do this using the Talon SRX firmware.
Will test on PlyBot.  CAN bus is wired up; need to test this with a basic Arcade Drive.
Need to build wiring harness between encoders and Talons.  For this, need parts that James is ordering.

**Comment by jwalthour** [comment]
Also need to use web interface to assign CAN bus IDs, and later to configure PID tuning parameters.

**Comment by setupminimal** [comment]
I think this counts as done.
